#!/bin/bash

out=src/boot.c

echo "// This file was generated by a terrible bash script." > src/boot.c
echo -n "const char *bootscript_data = \"" >> src/boot.c
hexdump -ve '1/1 "_x%02X"' $1 | sed 's/_/\\/g' >> src/boot.c
echo '";' >> src/boot.c
