#!/bin/bash

out=src/boot.c

echo "// This file was generated by a terrible bash script." > $out
echo -n "const char *bootscript_data = \"" >> $out
hexdump -ve '1/1 "_x%02X"' $1 | sed 's/_/\\/g' >> $out
echo '";' >> $out
