#!/bin/bash

cat << EOF > src/ffi_init.c
// This file was generated by a terrible bash script.
#include <lua.h>
#include <lualib.h>
#include <lauxlib.h>
#include <debugnet.h>

EOF

find src/ffi/ -type f -name '*.c' | while read f; do
	name=${f%.c}
	name=${name#src/ffi/}
	echo "void ffi_register_${name}();" >> src/ffi_init.c
done

echo >> src/ffi_init.c

cat << EOF >> src/ffi_init.c
void open_ffi(lua_State *l)
{
EOF
find src/ffi/ -type f -name '*.c' | while read f; do
	name=${f%.c}
	name=${name#src/ffi/}
	echo -e "\tffi_register_${name}();" >> src/ffi_init.c
done

echo '}' >> src/ffi_init.c
