#!/bin/bash

out=src/splash.c

echo "// This file was generated by a terrible bash script." > $out
echo -n "const char *splash_data = \"" >> $out
hexdump -ve '1/1 "_x%02X"' $1 | sed 's/_/\\/g' >> $out
echo '";' >> $out
echo "unsigned int splash_data_len = `wc -c $1 | grep -o '^[0-9]*'`;" >> $out
