#!/bin/bash

out=src/font.c

echo "// This file was generated by a terrible bash script." > $out
echo -n "const char *defaultfont_data = \"" >> $out
hexdump -ve '1/1 "_x%02X"' $1 | sed 's/_/\\/g' >> $out
echo '";' >> $out
echo "unsigned int defaultfont_data_len = `wc -c $1 | grep -o '^[0-9]*'`;" >> $out
