#include <stddef.h>
#include <stub_ffi.h>
#include <psp2/net/http.h>
void open_http()
{
	static Function funcs[] =
	{
		{"sceHttpInit", sceHttpInit},
		{"sceHttpTerm", sceHttpTerm},
		{"sceHttpGetMemoryPoolStats", sceHttpGetMemoryPoolStats},
		{"sceHttpSetAuthInfoCallback", sceHttpSetAuthInfoCallback},
		{"sceHttpSetAuthEnabled", sceHttpSetAuthEnabled},
		{"sceHttpGetAuthEnabled", sceHttpGetAuthEnabled},
		{"sceHttpSetRedirectCallback", sceHttpSetRedirectCallback},
		{"sceHttpSetAutoRedirect", sceHttpSetAutoRedirect},
		{"sceHttpGetAutoRedirect", sceHttpGetAutoRedirect},
		{"sceHttpSetResolveTimeOut", sceHttpSetResolveTimeOut},
		{"sceHttpSetResolveRetry", sceHttpSetResolveRetry},
		{"sceHttpSetConnectTimeOut", sceHttpSetConnectTimeOut},
		{"sceHttpSetSendTimeOut", sceHttpSetSendTimeOut},
		{"sceHttpSetRecvTimeOut", sceHttpSetRecvTimeOut},
		{"sceHttpSendRequest", sceHttpSendRequest},
		{"sceHttpAbortRequest", sceHttpAbortRequest},
		{"sceHttpGetResponseContentLength", sceHttpGetResponseContentLength},
		{"sceHttpGetStatusCode", sceHttpGetStatusCode},
		{"sceHttpGetAllResponseHeaders", sceHttpGetAllResponseHeaders},
		{"sceHttpReadData", sceHttpReadData},
		{"sceHttpAddRequestHeader", sceHttpAddRequestHeader},
		{"sceHttpRemoveRequestHeader", sceHttpRemoveRequestHeader},
//		{"sceHttpSetProxy", sceHttpSetProxy},
//		{"sceHttpGetProxy", sceHttpGetProxy},
//		{"sceHttpEnableKeepAlive", sceHttpEnableKeepAlive},
//		{"sceHttpDisableKeepAlive", sceHttpDisableKeepAlive},
//		{"sceHttpEnableHttp0_9", sceHttpEnableHttp0_9},
//		{"sceHttpDisableHttp0_9", sceHttpDisableHttp0_9},
		{"sceHttpParseResponseHeader", sceHttpParseResponseHeader},
		{"sceHttpParseStatusLine", sceHttpParseStatusLine},
		{"sceHttpCreateTemplate", sceHttpCreateTemplate},
		{"sceHttpDeleteTemplate", sceHttpDeleteTemplate},
		{"sceHttpCreateConnection", sceHttpCreateConnection},
		{"sceHttpCreateConnectionWithURL", sceHttpCreateConnectionWithURL},
		{"sceHttpDeleteConnection", sceHttpDeleteConnection},
		{"sceHttpCreateRequest", sceHttpCreateRequest},
		{"sceHttpCreateRequestWithURL", sceHttpCreateRequestWithURL},
		{"sceHttpDeleteRequest", sceHttpDeleteRequest},
//		{"sceHttpSetResponseHeaderMaxSize", sceHttpSetResponseHeaderMaxSize},
//		{"sceHttpSetRecvBlockSize", sceHttpSetRecvBlockSize},
		{"sceHttpSetRequestContentLength", sceHttpSetRequestContentLength},
		{"sceHttpUriEscape", sceHttpUriEscape},
		{"sceHttpUriUnescape", sceHttpUriUnescape},
		{"sceHttpUriParse", sceHttpUriParse},
		{"sceHttpUriBuild", sceHttpUriBuild},
		{"sceHttpUriMerge", sceHttpUriMerge},
		{"sceHttpUriSweepPath", sceHttpUriSweepPath},
		{"sceHttpsLoadCert", sceHttpsLoadCert},
		{"sceHttpsUnloadCert", sceHttpsUnloadCert},
		{"sceHttpsEnableOption", sceHttpsEnableOption},
		{"sceHttpsDisableOption", sceHttpsDisableOption},
		{"sceHttpsGetSslError", sceHttpsGetSslError},
		{"sceHttpsSetSslCallback", sceHttpsSetSslCallback},
		{"sceHttpsGetCaList", sceHttpsGetCaList},
		{"sceHttpsFreeCaList", sceHttpsFreeCaList},
		{"sceHttpSetCookieEnabled", sceHttpSetCookieEnabled},
		{"sceHttpGetCookieEnabled", sceHttpGetCookieEnabled},
		{"sceHttpGetCookie", sceHttpGetCookie},
		{"sceHttpAddCookie", sceHttpAddCookie},
		{"sceHttpSetCookieRecvCallback", sceHttpSetCookieRecvCallback},
		{"sceHttpSetCookieSendCallback", sceHttpSetCookieSendCallback},
		{NULL, NULL}
	};
	static FunctionTable table = { .funcs = funcs, .next = NULL };
	ffi_add_table(&table);
}
